pub mod base;
mod operator_overloads;
mod display;
mod format;
pub mod try_arithmetic;
pub mod functions;
pub mod transforms;
#[macro_use] pub mod macros;
//#[cfg(nightly)] pub mod matrix_simd_functions;
//#[cfg(nightly)] pub mod matrix_simd_transforms;
pub mod extras;